# Generated by Django 2.2.6 on 2019-10-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardName', models.CharField(max_length=50)),
                ('boardNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PostFree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('contents', models.TextField()),
                ('createDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
