# Generated by Django 2.2.6 on 2019-10-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posthobby',
            name='photo',
        ),
        migrations.CreateModel(
            name='HobbyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hobby/%Y/%m/%d')),
                ('posthobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.PostHobby')),
            ],
        ),
    ]
