# Generated by Django 2.2.6 on 2019-10-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='boardNumber',
        ),
        migrations.AlterField(
            model_name='posthobby',
            name='gender',
            field=models.CharField(choices=[('NO', 'Regardless'), ('MA', 'Male'), ('FE', 'Female')], default='NO', max_length=10),
        ),
        migrations.AlterField(
            model_name='posthobby',
            name='photo',
            field=models.ImageField(blank=True, upload_to='hobby/%Y/%m/%d'),
        ),
    ]
