# Generated by Django 2.2.6 on 2019-10-14 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191014_1537'),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentFree',
        ),
        migrations.RemoveField(
            model_name='commentfree',
            name='post',
        ),
        migrations.AddField(
            model_name='commentfree',
            name='postFree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boards.PostFree'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CommentHobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('postHobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.PostHobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
