# Generated by Django 2.2.6 on 2019-10-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20191021_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthobby',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hobby/%Y/%m/%d'),
        ),
    ]
