# Generated by Django 2.2.6 on 2019-10-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20191021_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='groupName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='boardName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='posthobby',
            old_name='createDate',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='sectionName',
            new_name='name',
        ),
    ]
