# Generated by Django 2.2.6 on 2019-10-14 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('userSex', models.CharField(max_length=20)),
                ('userAge', models.IntegerField()),
                ('userImage', models.ImageField(blank=True, upload_to='')),
                ('userGrade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PostOnetone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
