# Generated by Django 2.2.6 on 2019-10-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191018_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userImage',
            field=models.ImageField(blank=True, upload_to='userProfile/'),
        ),
    ]
