# Generated by Django 2.2.6 on 2019-10-14 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191014_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='user',
        ),
    ]
