# Generated by Django 2.2.6 on 2019-10-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_section_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userGrade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
